### ISSUE TITLE
Evaluation script/notebook needed for reproducing model zoo benchmarks

### ISSUE THREAD

**Issue by anisaha1** [facebookresearch/pytorchvideo#104]
Hi @kalyanvasudev @tullie,

Could you please provide an example of how to evaluate the model zoo pre-trained models to reproduce the benchmarks?
Specifically, the script should show how you generated the spatial and temporal crops of a video for evaluation.

Thanks.

**Comment by lyttonhao** [comment]
@anisaha1 Good to know that you already reproduced the numbers with pyslowfast. Yeah, the self-contained evaluation script would be available when we build our own trainer.
