### ISSUE TITLE
clip_index not reset to 0 between videos 

### ISSUE THREAD

**Issue by DianeBouchacourt** [facebookresearch/pytorchvideo#109]
I am using LabeledVideoDataset, and found out that self.cur_clip_index returned by the UniformClipSampler sampler is not reset to 0 between videos. 

Shouldn't we reset it here 

https://github.com/facebookresearch/pytorchvideo/blob/23335c7aa495ad7472ce6d0620f2484683523397/pytorchvideo/data/labeled_video_dataset.py#L170
Adding a line such as self._clip_sampler._current_clip_index = 0 when "is_last_clip" is True? Or reset it in the UniformClipSampler?

Note that ConstantClipsPerVideoSampler resets _current_clip_index indeed 
https://github.com/facebookresearch/pytorchvideo/blob/5c34ca13956425c63533923eebaf7c3b57acc71c/pytorchvideo/data/clip_sampling.py#L238

**Comment by kalyanvasudev** [comment]
Resolved in this commit - https://github.com/facebookresearch/pytorchvideo/commit/94cac77206ad49d912f8d2b6bbc5aadcba70db3e. Thanks raising the issue.
