### ISSUE TITLE
RandomShortSideScale interpolation and backend argument

### ISSUE THREAD

**Issue by ChickenTarm** [facebookresearch/pytorchvideo#117]
The api for the wrapper transforms functionals should be consistent: 
For RandomResizedCrop all of the underlying arguments for functional.random_resized_crop can be adjusted.
For RandomShortSideScale and ShortSideScale can only change the arguments for size while interpolation and backend cannot be changed.

This really applies to all wrapper apis, but these are the transforms I have been using so far.

**Comment by kalyanvasudev** [comment]
This has been resolved in this diff - https://github.com/facebookresearch/pytorchvideo/commit/94cac77206ad49d912f8d2b6bbc5aadcba70db3e
Please feel free to re-open the issue if you have further questions.
