### ISSUE TITLE
create_video_transform function raise data type error

### ISSUE THREAD

**Issue by leftthomas** [facebookresearch/pytorchvideo#123]
The function `create_video_transform ` contains `ConvertUint8ToFloat` transform default, but if we use `Kinetics` class  to load directory videos, the loaded videos is `float32` data type already, then when the video is processed by `ConvertUint8ToFloat`, it will raise the error of `image must have dtype torch.uint8`
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/9991443/134620165-b7719435-769d-4705-9170-21df6995d2a9.png">

**Comment by kalyanvasudev** [comment]
@leftthomas, yes, simply setting `convert_to_float=False` in input arguments of `create_video_transform` should do it. 

Please feel free to re-open the issue if you have further questions.

PS: I can see how return a float but in the rage [0,255] from `LabeledVideoDataset` can be unintuitive. I will update it either [0,1] with float type or [0,255] with uint type for the clip tensor in `LabeledVideoDataset` in a future refactor of LabeledVideoData.
