### ISSUE TITLE
Converting SlowFast detection model to deployable form

### ISSUE THREAD

**Issue by arunponnusamy** [facebookresearch/pytorchvideo#127]
I am trying to convert `Slow R50 4x16` detection model to TorchScript `.ptl` format to use in the Android app using the model conversion script [here](https://github.com/pytorch/android-demo-app/blob/master/TorchVideo/build_model.py).

``` 
convert_to_deployable_form(model, input_tensor) 
```
Above API from `pytorchvideo` accepts only two arguments. Model and only one input tensor to the model. This works well for classification models but detection models like Slow/SlowFast take two inputs - input frames and bounding box details.

Is there a way to use `convert_to_deployable_form( )` function with detection model ? 
Any help is really appreciated.

**Comment by kalyanvasudev** [comment]
@arunponnusamy, you could wrap the Detection model in your arbitrary custom `nn.Module` class that would take only one input argument and convert into 2 arguments needed by our detection model. 

Hope this answers your question. Feel free to re-open the issue if you have more questions.
