### ISSUE TITLE
Does pytorchvideo.data.encoded_video.EncodedVideo support batchload?

### ISSUE THREAD

**Issue by TianhaoFu** [facebookresearch/pytorchvideo#142]
Hi , Thanks for your code.

I wonder know does your data load function and preprocess function support batch operation?

Thanks:)

**Comment by kalyanvasudev** [comment]
I'm not sure if I follow, please refer to our tutorials and documention for more details - https://pytorchvideo.org/

**Comment by kalyanvasudev** [comment]
Please feel free to re-open the issue with more details if you have further questions
