### ISSUE TITLE
Load a set of pretrained weights on my current architecture

### ISSUE THREAD

**Issue by AntoninDuval** [facebookresearch/pytorchvideo#146]
Hi.
I recently changed my training workflow from using the repository PySlowFast to just PyTorchVideo in combination with PyTorch Lightning.

I create my network using the function `create_resnet` from PTV. I want to use a set of weights pre-trained on Kinetics with my current architecture. Is there a way to do this ?

In the documentation, it is only mention how to load a pre-trained model using torch.hub.load. How about loading just the weights and use them as a hot start with my own architecture ?

**Comment by lyttonhao** [comment]
Hi, thanks for playing with PTV. You can use the standard way (e.g. `load_state_dict`) to load/save checkpoint following this [doc](https://pytorch.org/tutorials/recipes/recipes/saving_and_loading_a_general_checkpoint.html#load-the-general-checkpoint)
