### ISSUE TITLE
train.py: error: the following arguments are required: --data_path at Train.py

### ISSUE THREAD

**Issue by SungmanHong** [facebookresearch/pytorchvideo#148]
I want to train the model, but when I run train.py

train.py: error: the following arguments are required: --data_path

comes out... how to set --data_path??? there is so few tutorials...T.T;;

**Comment by ZeynepP** [comment]
I am a beginner but I succeeded to run train.py for video classification example by following this : https://pytorchvideo.readthedocs.io/en/latest/data_preparation.html 

--data-path should point to the folder where you have train.csv, val.csv, test.csv. 

Hope it helps
Bests

**Comment by SungmanHong** [comment]
@ZeynepP Hi, I'm trying it. Thx. but The data size is too large and download speed is extreamly slow.... Should I can download the train data while 2~3 days? Thx. (I want to train my custom data, I just want to run train.py. Thx T.T)

**Comment by kalyanvasudev** [comment]
@SungmanHong, following instructions [here](https://pytorchvideo.readthedocs.io/en/latest/data_preparation.html), you should be able to setup the Kinetics dataset. 

Please re-open the issue if the problem persists. We also have have updated PyTorch-Lightning trainer here - https://github.com/facebookresearch/pytorchvideo/pull/158 which will be merged soon.
