### ISSUE TITLE
No saved model after train.py

### ISSUE THREAD

**Issue by SungmanHong** [facebookresearch/pytorchvideo#149]
train.py dose not save the model???

**Comment by kalyanvasudev** [comment]
Hi @SungmanHong , We are working on an overhauled training pipeline. It will be available in the next two weeks. Thanks!

**Comment by hyperf0cus** [comment]
> Hi @SungmanHong , We are working on an overhauled training pipeline. It will be available in the next two weeks. Thanks!

Hello! Is it coming?) Thanks!
