### ISSUE TITLE
How do I open a video, no labels, no weird stuff, just a normal video :)

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [facebookresearch/pytorchvideo#153]
## ❓ Questions on how to use PyTorchVideo

Pytorchvideo seems to be equipped with tons of amazing features. However, I was not able to find a way to open a video, just a video, with the library.

Thank you :)

Cheers,

Francesco

**Comment by kalyanvasudev** [comment]
Please use the EncodedVideo.from_path method - https://github.com/facebookresearch/pytorchvideo/blob/main/pytorchvideo/data/encoded_video.py#L48
