### ISSUE TITLE
unable to load video via LabeledVideoDataset

### ISSUE THREAD

**Issue by talhaanwarch** [facebookresearch/pytorchvideo#161]
Here is the dame frame, containing path 
```
	group     label	path
0	17	        90	../../splitvideos/17/0/0.avi
1	17		90	../../splitvideos/17/0/1.avi
2	17		91	../../splitvideos/17/0/2.avi
3	17		90	../../splitvideos/17/1/0.avi
4	17		90	../../splitvideos/17/1/1.avi
```
I passed it as follow
```
train_dataset=LabeledVideoDataset(labeled_video_paths=(list(train_df.path),list(train_df.pulse)),
                   clip_sampler=make_clip_sampler("random", 2),decode_audio=False)
train_loader=DataLoader(train_dataset,batch_size=2)
```
But when i do 
`batch=next(iter(train_loader))`
it throws error `StopIteration`

EDIT:
I changed the code to 
```
train_dataset=LabeledVideoDataset(labeled_video_paths=list(zip(train_df.path,train_df.pulse)),
```
but now i am getting error when i run `batch=next(iter(train_loader))`

```
TypeError: 'int' object is not a mapping
```
This issue is because of the following line, which in my case return a label.
 https://github.com/facebookresearch/pytorchvideo/blob/6744240a239b615bdc3ab3e2b795977a4db38848/pytorchvideo/data/labeled_video_dataset.py#L213

**Comment by talhaanwarch** [comment]
I believe this line 
https://github.com/facebookresearch/pytorchvideo/blob/6744240a239b615bdc3ab3e2b795977a4db38848/pytorchvideo/data/labeled_video_dataset.py#L213
should be replaced with
```
"info_dict":info_dict,
```

**Comment by kalyanvasudev** [comment]
@talhaanwarch, you are not using `LabeledVideoDataset` correctly. `labeled_video_paths` should a list of dictionaries i.e, each element in the list is a dictionary. And each dictionary contains lablels and other information associated with a single clip.

Please refer to our documentation for more details. 

An example of `labeled_video_paths` can be found at - https://github.com/facebookresearch/pytorchvideo/blob/main/pytorchvideo/data/labeled_video_paths.py#L13

Closing the issue now. Feel free to re-open it if you have more questions.

**Comment by talhaanwarch** [comment]
@kalyanvasudev can you please provide a sample dictionary
