### ISSUE TITLE
Redundant normalization by lambda and Normalize transform

### ISSUE THREAD

**Issue by talhaanwarch** [facebookresearch/pytorchvideo#167]
In augmentation section of tutorials, videos are normalized both by lambda and normalize class.
```
Lambda(lambda x: x / 255.0),
Normalize((0.45, 0.45, 0.45), (0.225, 0.225, 0.225)),
```
According to my understanding, video frames are divided by 255 to normalize it. But then it is again normalized. 
Is not this behavior is redundant?

**Comment by dienhoa** [comment]
No, I think it's not redundant. The Lambda is for scaling your image to [0,1] scale ( by default it is [0,255] ). Then it is normalized by the means and variances of this scale ([0,1])

**Comment by talhaanwarch** [comment]
in pytorch we never normalize image as image/255, we usually normalize it by Normalize((0.45, 0.45, 0.45), (0.225, 0.225, 0.225)), though the image is between 0-255

**Comment by dienhoa** [comment]
The stats you have here, for example: means [0.45, 0.45, 0.45] , variances [0.225,0.225,0.225] are in [0,1] scale . It's evident because it's hard images in 0-255 scale have such small variance.

You first changing the scale to 0-1 then normalizing with the stats

**Comment by haooooooqi** [comment]
The first "norm" adjusts it's scale, the second "norm" adjusts its mean and std
