### ISSUE TITLE
Loading labeled dataset error with path -- pytorchvideo.data.labeled_video_dataset: Failed to load video with error: "Kinetics700_2020/kinetics700_2020/kinetic_validate/shining flashlight/6qM_YEFgMV8_000149_000159.mp4" not found.; trial 0

### ISSUE THREAD

**Issue by ccapontep** [facebookresearch/pytorchvideo#175]
## Question on how to load labeled dataset correctly in PyTorchVideo

Related to issue: https://github.com/facebookresearch/pytorchvideo/issues/50

I am still trying to get the labeled dataset loaded correctly. It still does not recognize the paths given, even though I am following the instructions above. What is the correct way to provide the video path in order to load correctly in:

` self.train_dataset = LimitDataset(  pytorchvideo.data.Kinetics(
                                                        data_path=os.path.join(self.args.data_path, "train.csv"),
                                                        clip_sampler=pytorchvideo.data.make_clip_sampler(  "random", self.args.clip_duration  ),
                                                        video_path_prefix=self.args.video_path_prefix,
                                                        transform=train_transform,
                                                        video_sampler=sampler,  ) )
`

See setup of paths and locations below:

pytorchvideo.data.labeled_video_dataset: Failed to load video with error: "Kinetics700_2020/kinetics700_2020/kinetic_validate/shining flashlight/6qM_YEFgMV8_000149_000159.mp4" not found.; trial 0

In validate.csv file:
Kinetics700_2020/kinetics700_2020/kinetic_validate/shining flashlight/6qM_YEFgMV8_000149_000159.mp4 134

Location of video:
/content/gdrive/MyDrive/Deep_Vision/PyVideo/Kinetics700_2020/kinetics700_2020/kinetic_validate/shining flashlight/6qM_YEFgMV8_000149_000159.mp4

Current working directory:
/content/gdrive/MyDrive/Deep_Vision/PyVideo

Datapath:
--data_path 'Kinetics700_2020'

Video datapath: none
--video_path_prefix ""

I have tried various combinations between video_path_prefix and the paths of the videos in the csv files, but still get the same error. I have also checked that the video is in fact in the path shown.

I appreciate in advance the help.

**Comment by soltkreig** [comment]
I have the same. Any solutions?

**Comment by juliendenize** [comment]
Basically, the paths are computed [here](https://github.com/facebookresearch/pytorchvideo/blob/a5cc0c8a3e1c3f8c963b75e0bd5409650ad7616a/pytorchvideo/data/labeled_video_paths.py#L125-L134).

In your case self._path_prefix is `''` and path is provided by the csv file as `Kinetics700_2020/kinetics700_2020/kinetic_validate/shining flashlight/6qM_YEFgMV8_000149_000159.mp4`

Have you tried the absolute path `video_path_prefix` to the root video directory? Also, I understand that you want to use the relative path but you probably need to indicate you want to use a relative path. Based on your working directory and the paths you provided, here are the two options you can try:
- absolute path: `--video_path_prefix '/content/gdrive/MyDrive/Deep_Vision/PyVideo/'`
- relative path: `--video_path_prefix './'

**Comment by lyttonhao** [comment]
@juliendenize Thanks for replying it. Yes, please make sure if you provide the right absolute or relative path for the videos.
