### ISSUE TITLE
more/better documentation needed on creating datasets

### ISSUE THREAD

**Issue by jjones203** [facebookresearch/pytorchvideo#177]
## 🚀 Feature
The tutorials do not provide enough information for those of us who want to run models using our own video data.

## Motivation
I'm reiterating the concern voiced in [this issue](https://github.com/facebookresearch/pytorchvideo/issues/40). I have spent hours going through your code and trying different things with no success. When I try to use my LabeledVideoDataset, I keep getting the error message, "RuntimeError: Failed to load video after 10 retries.", which doesn't really help me with debugging.

## Pitch
If people have difficulty using `pytorchvideo` on their data, they will choose a different library (which I am beginning to consider). Please include an example users can adapt for use with their own data.

**Comment by lyttonhao** [comment]
Hi, thanks for playing with pytorchvideo. We provide the dataset preparation for different supported video datasets in this data preparation [doc](https://pytorchvideo.readthedocs.io/en/latest/data_preparation.html). It includes single-label video dataset (e.g Kinetics), multi-label video datasets (e.g. Charades) and video detection datasets (e.g. AVA). 
For your own datasets, if your datasets follows in the current categories, you can create split files and prepare the dataset folder following the instructions in the above document.
