### ISSUE TITLE
Handling imbalance in video datasets

### ISSUE THREAD

**Issue by dudeperf3ct** [facebookresearch/pytorchvideo#181]
I have a highly imbalanced video dataset. There are three different approaches that can taken

1. Weighted Cross Entropy Loss
2. Weighted Random Sampler to ensure more number of less frequent classes are sampled with higher probability in each batch of training dataset.
3. Adding video augmentation to less frequent class such that we get balanced training dataset of equal number of samples per class - How can this be achieved using PyTorchVideo?

How to add support for [WeightedRandomSampler](https://pytorch.org/docs/stable/data.html#torch.utils.data.WeightedRandomSampler)  as an alternative [video sampler](https://github.com/facebookresearch/pytorchvideo/blob/5e585415bde879756f60b8864b78e87c102c6abc/pytorchvideo/data/labeled_video_dataset.py#L32)?

I tried replacing the `video_sampler` with `WeightedRandomSampler` but it gives following error.

```bash
  File "/opt/conda/lib/python3.8/site-packages/pytorchvideo/data/labeled_video_dataset.py", line 75, in __init__
    self._video_sampler = video_sampler(self._labeled_videos)
TypeError: 'WeightedRandomSampler' object is not callable
```

**Comment by haooooooqi** [comment]
Hi,
I am not sure you did you passed it, maybe you can pass it with:
```
LabeledVideoDataset(video_sampler=partial(torch.utils.data.WeightedRandomSampler, weights=weights, num_samples=num_samples)
```
