### ISSUE TITLE
Is PyTorchVideo going to release the code for reproducing the Models Zoo using PyTorchVideo and not PySlowFast?

### ISSUE THREAD

**Issue by guglielmocamporese** [facebookresearch/pytorchvideo#183]
Currently the model checkpoints reported in the official Model Zoo of PyTorchVideo [[here](https://pytorchvideo.readthedocs.io/en/latest/model_zoo.html)] are obtained using the PySlowFast repo [[here](https://github.com/facebookresearch/SlowFast)]. I'm wondering if PyTorchVideo is going to release the code to obtain such checkpoints even using the PyTorchVideo codebase.

Thank you!

**Comment by guglielmocamporese** [comment]
any updates?

**Comment by haooooooqi** [comment]
Hi @guglielmocamporese 
Currently we have built the PyTorcVideo STL training pipeline from [here](https://github.com/facebookresearch/pytorchvideo/tree/main/pytorchvideo_trainer).
