### ISSUE TITLE
Clip duration and num frames question

### ISSUE THREAD

**Issue by exnx** [facebookresearch/pytorchvideo#185]
## ❓ Questions on how to use PyTorchVideo

Hi, I am wondering how the dataloader handles durations or num_frames that are longer than the video sample.  For example, let's say I choose num_frames=64 and duration=4 secs, what would be returned if the number of frames or duration of the video is shorter?  (eg, video has 50 frames, or is 2 secs long?).  Would the input shape just be padded to cover 50 frames somehow?  What is it padded with?

Also, about the duration.  Does selecting the num_frames and duration implicitly manipulate the FPS?

Thanks!

**Comment by lyttonhao** [comment]
Hi, thanks for playing with PyTorchVideo. The actual sampled frames is depending on the sampling transform you used. For example, if you use the standard [UniformTemporalSample](https://github.com/facebookresearch/pytorchvideo/blob/main/pytorchvideo/transforms/transforms.py#L54) and `num_frames` is greater than the duration, we will sample nearest frames to make sure we still sample `num_frames` frames as implemented [here].(https://github.com/facebookresearch/pytorchvideo/blob/main/pytorchvideo/transforms/functional.py#L38)
