### ISSUE TITLE
How to extract i3d features from i3d_r50 model of pytorchvideo?

### ISSUE THREAD

**Issue by haiderzm** [facebookresearch/pytorchvideo#188]
I want to extract i3d features from video using pytorchvideo library but unable to find any relevant tutorial for that.

**Comment by kuangxiaoye** [comment]
me too

**Comment by Hongyuan-Liu** [comment]
me too

**Comment by lyttonhao** [comment]
Hi, thanks for your interest in pytorchvideo! If you want to do feature extraction, it would be similar to the actual model inference but you create the model without prediction head. For example, for the [torch hub models](https://github.com/facebookresearch/pytorchvideo/blob/main/pytorchvideo/models/hub/resnet.py#L126), you could pass `head=None` for kwargs to remove the prediction heads when [creating models](https://github.com/facebookresearch/pytorchvideo/blob/e3fc8fb4d1ea8dfb0aea3b1064b58fa84c97b97c/pytorchvideo/models/resnet.py#L646)
