### ISSUE TITLE
How to finetune SlowFast pretrained model on custom AVA dataset in PytorchVideo?

### ISSUE THREAD

**Issue by Balakishan77** [facebookresearch/pytorchvideo#197]
I want to perform custom training(finetune) on my dataset(AVA format) using pretrained slowfast model from Pytorchvideo model zoo. 
****
slowfast model link: https://dl.fbaipublicfiles.com/pytorchvideo/model_zoo/ava/SLOWFAST_8x8_R50_DETECTION.pyth
***
I am unable to find anything related to this in documentation. Could someone help me on this?

**Comment by C-popKingJames** [comment]
我也想知道如何用pytorchvideo训练自己的数据集

**Comment by kalyanvasudev** [comment]
Hi We don't have plans to support this Pytorchvideo anytime soon. I'd encourage users to the AVA benchmarks in pyslowfast repo to do this - https://github.com/facebookresearch/slowfast
