### ISSUE TITLE
Why does `UniformClipSampler` prevent stride from being greater than duration?

### ISSUE THREAD

**Issue by dasturge** [facebookresearch/pytorchvideo#201]
## ❓ Questions on how to use PyTorchVideo

There's a check at the end of `UniformClipSampler` to assert that stride is not greater than the clip duration, I'm wondering if there's a practical reason this causes some sort of issue or if it's supposed to just be a safety put in to prevent the user from doing something they might not want.  

I encountered this when trying to use a 'frame-level' model (2D CNN), where I set clip_duration=1 / video_frame_rate and clip_stride=1 second so I could load 1 frame each second.

**Comment by kalyanvasudev** [comment]
HI @dasturge , I'd change to basically sample 1 second clip and leave the stride unset. Then later you could use the [UniformTemporalSubsample](https://github.com/facebookresearch/pytorchvideo/blob/main/pytorchvideo/transforms/transforms.py#L54) transform to get a single frame from the clip.
