### ISSUE TITLE
Convert x3d model to torchscript

### ISSUE THREAD

**Issue by hongsamvo** [facebookresearch/pytorchvideo#210]
## 🐛 Bugs / Unexpected behaviors
Hi, I am trying to convert x3d model to TensorRT using torch_tensorrt and I got problem when I try to convert model to torch script. Please refer to this [issue](https://github.com/pytorch/TensorRT/issues/1160).
Thanks!!!

**Comment by RafayAK** [comment]
@hongsamvo if you have found an way to convert the model to torchscript, please share. It would be greatly appreciated. Thanks!

**Comment by hongsamvo** [comment]
Hi, I remembered that I can't convert this model to torchscript

**Comment by RafayAK** [comment]
Oh, that is unfortunate. The project also seems to be abandoned.

**Comment by RafayAK** [comment]
@hongsamvo Oh, that is unfortunate. The project also seems to be abandoned.
