### ISSUE TITLE
I3D Transform

### ISSUE THREAD

**Issue by Camillo4eyes** [facebookresearch/pytorchvideo#223]
Where i can find the correct tranform for the I3D model?

**Comment by mvidela31** [comment]
Hi @Camillo4eyes, 

Did you find the transform for the I3D model? Can you share it please?

**Comment by davimedio01** [comment]
@mvidela31 i have the same question, but you can use https://pytorch.org/hub/facebookresearch_pytorchvideo_resnet/ that works fine! Also, tested in PyTorch 2.0.0 with CUDA 11.8 here with a NVIDIA RTX 4060 =)
