### ISSUE TITLE
How to save .pt from ckpt?

### ISSUE THREAD

**Issue by hyuDev** [facebookresearch/pytorchvideo#25]
Hello I trained model with custom dataset for video classification.
and I get a weights file(.ckpt). but I want to use it android app(https://github.com/pytorch/android-demo-app/tree/master/TorchVideo). 

How to save .pt from ckpt?
and I want to test(or demo) a video clip using my model. your test code is not working. help me

**Comment by liyilui** [comment]
Please check https://github.com/pytorch/android-demo-app/blob/master/TorchVideo/build_model.py, line 20-22. Basically the pt file is TorchScript, so you need to save your trained pytorch model into TorchScript file.

**Comment by hyuDev** [comment]
@liyilui thanks to reply, I try it. 
build_model.py is downloading pretrained model and using pyth. 
I train my model to following pytorchvideo tutorial( video classification) so the class number is different. 
also the tutorial not have torch.save(model), saving weights file to "ckpt" format not pyth.  
when I try to load save ckpt file, torch.load return this.
RuntimeError: Error(s) in loading state_dict for EfficientX3d:
	Missing key(s) in state_dict: "s1.pathway0_stem_conv_xy.kernel.conv.weight", "s1.pathway0_stem_conv.kernel.conv.weight", "s1.pathway0_stem_conv.kernel.bn.weight", "s1.pathway0_stem_conv.kernel.bn.bias", "
Unexpected key(s) in state_dict: "epoch", "global_step", "pytorch-lightning_version", "state_dict", "callbacks", "optimizer_states", "lr_schedulers".
 
i didn't not save with data parallel because it raise error.

what can i do?

**Comment by liyilui** [comment]
Instead of using build_model.py to create TorchScript, you should create your own TorchScript file (.pt). 
After you train your model, use 
`trace_model = torch.jit.trace(model, example_input_tensor)`
`trace_model.save('model.pt')`
to get the pt file.
Please also refer to https://pytorch.org/docs/stable/generated/torch.jit.trace.html

**Comment by SungmanHong** [comment]
how to change ckpt to pt...? T.T

**Comment by Matesanz** [comment]
> how to change ckpt to pt...? T.T

Please, read @liyilui comment carefully.

Based on his answer and reading the documentation:

```python
import torch
import torch.nn as nn

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv = nn.Conv2d(1, 1, 3)

    def forward(self, x):
        return self.conv(x)

n = Net()
example_weight = torch.rand(1, 1, 3, 3)
example_forward_input = torch.rand(1, 1, 3, 3)

# Trace a specific method and construct `ScriptModule` with
# a single `forward` method
module = torch.jit.trace(n.forward, example_forward_input)

# Trace a module (implicitly traces `forward`) and construct a
# `ScriptModule` with a single `forward` method
module = torch.jit.trace(n, example_forward_input)
```

**Comment by tomtao008** [comment]
AttributeError: type object 'Net' has no attribute 'load_from_checkpoint'

**Comment by tomtao008** [comment]
> AttributeError: type object 'Net' has no attribute 'load_from_checkpoint'

**Comment by raj-sivakumar** [comment]
@tomtao008 Did you eventually resolve your AttributeError?
