### ISSUE TITLE
AssertionError: input for MultiPathWayWithFuse needs to be a list of tensors

### ISSUE THREAD

**Issue by jiarenyf** [facebookresearch/pytorchvideo#27]
![image](https://user-images.githubusercontent.com/12405578/116238029-7763ea80-a793-11eb-8dc0-1d020db5cfe6.png)

Using 'slowfast_r50', the error is:
AssertionError: input for MultiPathWayWithFuse needs to be a list of tensors

**Comment by jiarenyf** [comment]
Any help please ...

**Comment by TimoMartens** [comment]
Hi, I'm having the same issue, may I ask how this was solved?

**Comment by kalyanvasudev** [comment]
Hi @TimoMartens, in order for me to debug, could you please provide more details and possibly the entire stack trace? Thanks!

**Comment by TimoMartens** [comment]
Hi @kalyanvasudev, I've been using the backbone with Lightning Flash and I believe there is a problem with the integration there. I've also posted an issue on their repository, maybe you can have a look at it as it also shows the stacktrace.
https://github.com/PyTorchLightning/lightning-flash/issues/631

**Comment by FraPochetti** [comment]
@TimoMartens thanks for your reply! Super weird this features as the first go-to tutorial on both lightning-flash and pytorch-video, and nobody is fixing that. I am quite confused

**Comment by FraPochetti** [comment]
@kalyanvasudev Holy moly man! Then I apologize for not going through the docs as thoroughly as I should have done.
