### ISSUE TITLE
Loading videos at a desired frame rate (fps) 

### ISSUE THREAD

**Issue by giladsharir** [facebookresearch/pytorchvideo#29]
## 🚀 Feature
Enable the ```EncodedVideoDataset``` class to accept an ```fps``` argument which will determine the fps in which the videos are read

## Motivation
Several action recognition method make use of lowering the input fps as a way of reducing computational load.  (e.g. https://arxiv.org/abs/2103.13915) . 
Currently there is no way of using the Kinetics dataset with a required fps.  It would also be useful to specify the desired number of frames per clip, and get a clip with uniformly sampled frames from the whole video.

**Comment by kalyanvasudev** [comment]
Hi, fps can be modulated and controlled using our [UniformTemporalSubsample](https://github.com/facebookresearch/pytorchvideo/blob/master/pytorchvideo/transforms/transforms.py#L53) data transform.

**Comment by kalyanvasudev** [comment]
Feel, free to re-open the issue if you have more questions about the same.
