### ISSUE TITLE
C2D with torch hub not possible?

### ISSUE THREAD

**Issue by Shiro-LK** [facebookresearch/pytorchvideo#30]
## ❓ Questions on how to use PyTorchVideo

Hello,

Thank you for releasing this nice framework for video domain.

I was wondering if it is possible to use the C2D model with this library ? In fact, it is mention in the benchmarking of pytorchvideo, but it seems not possible to use it with the torch.hub method, as it is not mentionned in the hubconf.py
Is there another way to use the C2D model ?

**Comment by lyttonhao** [comment]
Hi, thanks for your interest in PyTorchVideo. We plan to release more torch hub models including C2D very soon. 
Another way to use C2D or other customized models could be directly using `create_resnet` function to create models.

**Comment by lyttonhao** [comment]
The C2D hub model has already been supported in PTV. Please check [here](https://github.com/facebookresearch/pytorchvideo/tree/master/pytorchvideo/models/hub) for the full list of hub models.
