### ISSUE TITLE
Should add `Lambda(lambda x: x/255.0)` in tutorial

### ISSUE THREAD

**Issue by jiarenyf** [facebookresearch/pytorchvideo#32]
Should add `Lambda(lambda x: x/255.0)` in tutorial, right ?

**Comment by kalyanvasudev** [comment]
Yes, it does seem like we are missing the lambda scaling transform.

@tullie , could you please confirm this? We seem to have this transform for Pytorchvideo models in PySlowFast - https://github.com/facebookresearch/SlowFast/blob/master/slowfast/datasets/ptv_datasets.py#L194

**Comment by tullie** [comment]
Yep you're right! Great catch. Will send out a change for this.

**Comment by nateraw** [comment]
@tullie feel free to assign this to me :smile:

**Comment by tullie** [comment]
That sounds good @nateraw!

**Comment by kalyanvasudev** [comment]
@nateraw, it would be helpful if you could do a separate quick PR for this issue and tag the issue in the PR. This way, it will be better documented and sets up a nice example workflow for other contributors to follow :) Thanks a lot!

**Comment by nateraw** [comment]
@kalyanvasudev done! :smile:
