### ISSUE TITLE
Ava Dataset Loader

### ISSUE THREAD

**Issue by Vignesh1230** [facebookresearch/pytorchvideo#36]
## 🚀 Feature
Request: Implementation for AVA Dataset for localized human actions research

## Motivation

We're doing some work into action recognition models with localised actions in a frame, using the other facebookresearch slowfast repo. This implementation seems like a better way to go in terms of development, but currently stuck because we have our own dataset formatted on AVA.
 

## Pitch

To be able to train slowfast models using AVA dataset! Would be willing to help in the creation of the DataLoader as well.

**Comment by kalyanvasudev** [comment]
Hi, thank you for your request. We have now AVA Dataloder in PyTorchVideo.
