### ISSUE TITLE
ImportError: cannot import name 'Normalize' from 'pytorchvideo.transforms'

### ISSUE THREAD

**Issue by zhiweiguo** [facebookresearch/pytorchvideo#38]
ImportError: cannot import name 'Normalize' from 'pytorchvideo.transforms.transforms'

**Comment by jloveric** [comment]
Looks like pip just needs to be updated (Normalize doesn't exist in Transforms there).  Pulling directly from the get repo works fine.

**Comment by kalyanvasudev** [comment]
Thanks for pointing this out, as mentioned in the installation instructions, only the major/minor version changes affect the build for the command `pip install pytorchvideo`.

However, our nightly build (which can be installed using `pip install pytorchvideo-nightly`) get updated every night. 

To also make things consistent,  going forward, we also plan on doing weekly minor version and monthly major version releases. This should ensure that  `pip install pytorchvideo` is not outdated in comparison to the github repo.
