### ISSUE TITLE
How to use this library to develop my own video classification model

### ISSUE THREAD

**Issue by Epiphqny** [facebookresearch/pytorchvideo#40]
I want to use the default dataset code and change the model file, Are there any instructions about training and inference code to reproduce the existing model results and develop my own model, thanks!

**Comment by kalyanvasudev** [comment]
Please take a loot at our tutorials
1. Training your own model - https://pytorchvideo.org/docs/tutorial_classification
2. Inference using the models we provide - https://pytorchvideo.org/docs/tutorial_torchhub_inference

Please re-open the issue with further elaboration if the above tutorials do not answer your queries.

**Comment by trigal** [comment]
I believe that the tutorial should at least specify how the data folder structure should be (for training). Or at lease a screenshot, something more than a link to a dataset to download. And also, some hint saying that the tutorial use dataset with mp4 inputs. I'm saying this because I'm trying to test the train.py script modifying it to use my "per-frame" dataset, that I'm trying to adapt to Charades... but starting from "no info about this package", it's a little tricky :-(

**Comment by kalyanvasudev** [comment]
Hi, to get our faster attention, please consider re-opening the issue in future :)

To answer your questions.
- Encoded video datasets (.mp4, .webm,.avi,etc) and frame video datasets are treated the same by our pipelines once they are loaded. If you are using the `LabeledVideoDataset` it automatically can handle both frame video and encoded video datasets without changing much of the code.  
- In case of Charades, please take a look at our API documentation here to get an idea of the dataloader is constructed and what it returns (https://pytorchvideo.readthedocs.io/en/latest/api/data/data.html ) As you can observe, the API is no different from `LabeledVIdeoData` API in the same link.
- And in regards to data preparation, please take a look our Data docs here - https://pytorchvideo.readthedocs.io/en/latest/data_preparation.html

I hope this answers your questions. Please feel free to close the issue if it does.

**Comment by kalyanvasudev** [comment]
Hope my previous response answers the question. Closing the issue because of inactivity.

**Comment by SungmanHong** [comment]
Hi, in the training tutorials, the input glob size is same in android demo app?
