### ISSUE TITLE
Does the X3D model localize the region where the action is recognized? If so, how do I visualize these results?

### ISSUE THREAD

**Issue by ramyapriya** [facebookresearch/pytorchvideo#46]
Hi! I have tried using the recommended action recognition models on pre-existing videos. I would like to visualize the results as shown in this video - https://www.youtube.com/watch?v=b7-gnpqz9Qg&ab_channel=FacebookAI

**Comment by kalyanvasudev** [comment]
Hi, We are finalizing exclusive detection only tutorials with the visualizations as shown in the video. We will make the tutorial public by early next week.
