### ISSUE TITLE
[help want] change to custom pt model in android demo app, it's failed.

### ISSUE THREAD

**Issue by hyuDev** [facebookresearch/pytorchvideo#47]

**Comment by liyilui** [comment]
In the demo app, the input is (1, 3, 4, 160, 160), which is different from your model training/saving. You may need to change the input blob size in demo app for your model to work, and I believe you can find more details/ask question [there](https://github.com/pytorch/android-demo-app/tree/master/TorchVideo)

**Comment by hyuDev** [comment]
@liyilui hi, I knowthatso I change a relative part of code (1,3,4,160,160) to (4,3,8,256,256).
But the app is crushed with that error msg. Is it still a problem of my pt model? And I don't confirmed that my build_model.py is right evenif they dont use ckptfile. They are Just callback in code.

**Comment by liyilui** [comment]
According to the error message, I don’t think the change of input blob size is successful (as it is showing T=4 not 8). I would suggest ask in demo app github repo for best way to change or validate changing input blob size.

**Comment by kalyanvasudev** [comment]
Closing the issue due to inactivity. Please feel free to re-open the issue if the problem is not resolved.
