### ISSUE TITLE
pytorchvideo.data.labeled_video_dataset: Failed to load video with error: video/_104.avi not found.; trial 0

### ISSUE THREAD

**Issue by mrclasalvia** [facebookresearch/pytorchvideo#50]
Hi everyone,
I am trying to use a custom dataset with pytorchvideo following the tutorial for training, however, I am getting the following error: pytorchvideo.data.labeled_video_dataset: Failed to load video with error: video/_104.avi not found.; trial 0
I have created the csv files formatted as written in the data preparation tutorial as "path_to_video label".
the datapath directory I specified is the one containing train.csv and val.csv and also in the same directory there is a "video" folder where the videos are, as suggested from the error the path says "video/_104.avi".

How can I fix?

Thanks!

**Comment by tullie** [comment]
The paths should be relative to your current working directory not to the directory that contains the train.csv or val.csv. You could set the path_prefix arg to the same directory as the train/val.csv's if you don't want to change the paths in the csvs.

**Comment by ccapontep** [comment]
I am still trying to get the labeled dataset loaded correctly. It still does not recognize the paths given, even though I am following the instructions above. Could you provide more guidance please?

pytorchvideo.data.labeled_video_dataset: Failed to load video with error: "Kinetics700_2020/kinetics700_2020/kinetic_validate/shining flashlight/6qM_YEFgMV8_000149_000159.mp4" not found.; trial 0

In validate.csv file:
Kinetics700_2020/kinetics700_2020/kinetic_validate/shining flashlight/6qM_YEFgMV8_000149_000159.mp4 134

Location of video:
/content/gdrive/MyDrive/Deep_Vision/PyVideo/Kinetics700_2020/kinetics700_2020/kinetic_validate/shining flashlight/6qM_YEFgMV8_000149_000159.mp4

Current working directory:  
/content/gdrive/MyDrive/Deep_Vision/PyVideo

Datapath:
--data_path 'Kinetics700_2020'

Video datapath: none
--video_path_prefix ""

I have tried various combinations between video_path_prefix and the paths of the videos in the csv files, but still get the same error. I have also checked that the video is in fact in the path shown.

I appreciate in advance the help.
