### ISSUE TITLE
Load Channel Separated Network

### ISSUE THREAD

**Issue by mrclasalvia** [facebookresearch/pytorchvideo#58]
Hi everyone!

Can someone help me understand how do I load a CSN from torch hub? is it possible?

Thanks!

**Comment by kalyanvasudev** [comment]
CSN pretrained torchub model can load by simply calling the following,
```
from pytorchvideo.models.hub import csn_r101
csn_model  = csn_r101(True)
```

**Comment by mrclasalvia** [comment]
> CSN pretrained torchub model can be loaded by simply doing the following,
> 
> ```python
> from pytorchvideo.models.hub import csn_r101
> csn_model  = csn_r101(True)
> ```

How can I change the number of classes at this point then?
