### ISSUE TITLE
Input error

### ISSUE THREAD

**Issue by Mathuran-Mang** [facebookresearch/pytorchvideo#62]
While I was following the "Running a pre-trained PyTorchVideo classification model using Torch Hub" tutorial I am getting this error when I call preds = model(inputs). I only get this error when I use "slowfast_r50" as the model name. When I change the model name to slow_r50 it works fine.

RuntimeError                              Traceback (most recent call last)
<ipython-input-62-ed1a6c02c085> in <module>
----> 1 preds = model(inputs)

~\anaconda3\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
    887             result = self._slow_forward(*input, **kwargs)
    888         else:
--> 889             result = self.forward(*input, **kwargs)
    890         for hook in itertools.chain(
    891                 _global_forward_hooks.values(),

~\pytorchvideo\pytorchvideo\models\net.py in forward(self, x)
     41     def forward(self, x: torch.Tensor) -> torch.Tensor:
     42         for idx in range(len(self.blocks)):
---> 43             x = self.blocks[idx](x)
     44         return x
     45 

~\anaconda3\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
    887             result = self._slow_forward(*input, **kwargs)
    888         else:
--> 889             result = self.forward(*input, **kwargs)
    890         for hook in itertools.chain(
    891                 _global_forward_hooks.values(),

~\pytorchvideo\pytorchvideo\models\net.py in forward(self, x)
     85         for pathway_idx in range(len(self.multipathway_blocks)):
     86             if self.multipathway_blocks[pathway_idx] is not None:
---> 87                 x_out[pathway_idx] = self.multipathway_blocks[pathway_idx](
     88                     x[pathway_idx]
     89                 )

~\anaconda3\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
    887             result = self._slow_forward(*input, **kwargs)
    888         else:
--> 889             result = self.forward(*input, **kwargs)
    890         for hook in itertools.chain(
    891                 _global_forward_hooks.values(),

~\pytorchvideo\pytorchvideo\models\stem.py in forward(self, x)
    251 
    252     def forward(self, x: torch.Tensor) -> torch.Tensor:
--> 253         x = self.conv(x)
    254         if self.norm is not None:
    255             x = self.norm(x)

~\anaconda3\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
    887             result = self._slow_forward(*input, **kwargs)
    888         else:
--> 889             result = self.forward(*input, **kwargs)
    890         for hook in itertools.chain(
    891                 _global_forward_hooks.values(),

~\anaconda3\lib\site-packages\torch\nn\modules\conv.py in forward(self, input)
    518                             self.weight, self.bias, self.stride, _triple(0),
    519                             self.dilation, self.groups)
--> 520         return F.conv3d(input, self.weight, self.bias, self.stride,
    521                         self.padding, self.dilation, self.groups)
    522 

RuntimeError: Expected 5--dimensional input for 5-dimensional weight [64, 3, 1, 7, 7], but got 4-dimensional input of size [1, 8, 256, 256] instead

**Comment by PVDoanh96** [comment]
You can change the input parameter as:
``` side_size = 256
mean = [0.45, 0.45, 0.45]
std = [0.225, 0.225, 0.225]
crop_size = 256
num_frames = 32
sampling_rate = 2
frames_per_second = 30
alpha = 4
```
And remember: slow-fast has two path data: [slow_pathway, fast_pathway]
You can see: [tutorial](https://pytorchvideo.org/docs/tutorial_torchhub_inference)

Have a nice day.

**Comment by Mathuran-Mang** [comment]
Thank you

**Comment by kalyanvasudev** [comment]
I hope @PVDoanh96's response settles it? Please reopen the issue if you have more questions.
