### ISSUE TITLE
RAM Crash on Google Colab

### ISSUE THREAD

**Issue by Mathuran-Mang** [facebookresearch/pytorchvideo#64]
I am trying to run the demo under pytorchvideo/tutorials/video_detection_example/video_detection_inference_tutorial.ipynb on Google Colab however when I try load the video using 

encoded_vid = pytorchvideo.data.encoded_video.EncodedVideo.from_path('theatre.webm')
print('Completed loading encoded video.')

Google colab crashes saying there is not enough RAM. Do I need to get Google Colab Pro to be able to run this Demo?

**Comment by kalyanvasudev** [comment]
Hi @Mathuran-Mang , did you change the clip sampling window for your new video? If you change video, please make sure to sample clips for inference in the valid video window.  Also, note that the video need not be of the format .webm, it can any (.mp4, .avi, etc) format acceptable by our EncodedVideo object.

**Comment by Mathuran-Mang** [comment]
Thank you @kalyanvasudev changing the clip sampling window fixed the problem for me, however I cannot find where the predictions are stored. After it finished generating predictions where are the predictions or the video with the predictions stored?

**Comment by aofrancani** [comment]
I'm also having this issue when running the following line for the 'theatre.webm' example:
``` python 
encoded_vid = pytorchvideo.data.encoded_video.EncodedVideo.from_path('theatre.webm')
print('Completed loading encoded video.')
```
my Google Colab's session is crashing due to full RAM even with Colab Pro (high-RAM)... Is it possible to run this example on Colab?

**Comment by aofrancani** [comment]
> I'm also having this issue when running the following line for the 'theatre.webm' example:
> 
> ```python
> encoded_vid = pytorchvideo.data.encoded_video.EncodedVideo.from_path('theatre.webm')
> print('Completed loading encoded video.')
> ```
> 
> my Google Colab's session is crashing due to full RAM even with Colab Pro (high-RAM)... Is it possible to run this example on Colab?

It worked for me after converting '.webm' to '.mp4'

**Comment by m-ali-awan** [comment]
> Thank you @kalyanvasudev changing the clip sampling window fixed the problem for me.

Kindly, tell me where we can change the clip_sampling_window.

thanks
