### ISSUE TITLE
fvcore required version

### ISSUE THREAD

**Issue by wldwldcrd** [facebookresearch/pytorchvideo#66]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## 🐛 Bugs / Unexpected behaviors
detectron2 and pytorchvideo have contradicting requirements for fvcore

## Instructions To Reproduce the Issue:
1. I have Ubuntu 20.04, pytorch v.1.8.1+cu102, Cuda compilation tools, release 10.1, V10.1.243
2. So I tried to install detectron2 (https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md)
python -m pip install detectron2 -f \
  https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.8/index.html
3. And have this one error:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pytorchvideo 0.1.1 requires fvcore>=0.1.4, but you have fvcore 0.1.3.post20210317 which is incompatible.
4. So I update fvcore: pip install -U fvcore
5. And get another error:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
detectron2 0.4+cu102 requires fvcore<0.1.4,>=0.1.3, but you have fvcore 0.1.5.post20210609 which is incompatible.

**Comment by PareshKamble** [comment]
Facing same issue.
Please provide a solution.

**Comment by kalyanvasudev** [comment]
Let me try replicating this. I will get back.

**Comment by kalyanvasudev** [comment]
Are you working inside a conda environment?

**Comment by wldwldcrd** [comment]
Yes, Conda + Ubuntu 20.04

**Comment by PareshKamble** [comment]
Me too. Conda in Ubuntu 18.04.

**Comment by kalyanvasudev** [comment]
Thanks for the catch!, I was able to re-produce it. We no longer are restricted to only Fvcore>0.1.4. It should also work with fvcore>=0.1.3. I will update the installation script accordingly and merge by EOD.

**Comment by kalyanvasudev** [comment]
This PR should resolve it - https://github.com/facebookresearch/pytorchvideo/pull/72

**Comment by kalyanvasudev** [comment]
Closing the issue since it has now been resolved in v0.1.2, please re-open the issue if the problem persists.
