### ISSUE TITLE
Loading and inference with a Charades pre-trained model

### ISSUE THREAD

**Issue by gorjanradevski** [facebookresearch/pytorchvideo#67]
I looking into how to load a pre-trained model (on other dataset except Kinetics). In particular, I want to load `slowfast`, pre-trained on Charades. For that, I tried the following.

```python

from pytorchvideo.models.hub.slowfast import _slowfast
import torch

root_url = "https://dl.fbaipublicfiles.com/pytorchvideo/model_zoo"
checkpoint_path = f"{root_url}/charades/SLOWFAST_8x8_R50.pyth"
slowfast = _slowfast(pretrained=True, checkpoint_path=checkpoint_path)

with torch.no_grad():
    output = slowfast([torch.rand(1, 3, 8, 224, 224), torch.rand(1, 3, 32, 224, 224)])
    # torch.Size([1, 400])
    print(output.size())
```

My questions are:

1. Since the model loading succeeds, why the model output still corresponds to the Kinetics 400 number of classes? I did expect an error, in the case the model architecture and the loaded model don't match?

2. I didn't find a concrete tutorial how to load the models?

3. Once the model is loaded, what is the right way to preprocess the video, so that it corresponds to the exact way of training, on the corresponding dataset?

<!--NOTE: Please look at the existing list of Issues tagged with the label ['question`](https://github.com/facebookresearch/pytorchvideo/issues?q=label%3Aquestion) or ['how-to`](https://github.com/facebookresearch/pytorchvideo/issues?q=label%3A%22how+to%22). **Only open a new issue if you cannot find an answer there**.

<!--Also note the following:

<!--1. If you encountered any errors or unexpected issues while using PyTorchVideo and need help resolving them,
   please use the "Bugs / Unexpected behaviors" issue template.

<!--2. We do not answer general machine learning / computer vision questions that are not specific to
	 PyTorchVideo, such as how a model works or what algorithm/methods can be
	 used to achieve X.

**Comment by TianhaoFu** [comment]
Hi, I use your code and came across such bug. Have you saw that?
```
RuntimeError: Error(s) in loading state_dict for Net:	size mismatch for blocks.6.proj.weight: copying a param with shape 
torch.Size([157, 2304]) from checkpoint, the shape in current model is torch.Size([400, 2304]).
	size mismatch for blocks.6.proj.bias: copying a param with shape torch.Size([157]) from checkpoint, the shape in current model is torch.Size([400]).
```

**Comment by kalyanvasudev** [comment]
@TianhaoFu , this error is correct and expected behaviour for above codesnippet. If you loading a Charades trained model, make sure you pass in additional overrides that are required for that particular model. 

i.e, for Charades, you above snippet should be modified as,
```python
slowfast = _slowfast(pretrained=True, checkpoint_path=checkpoint_path, model_num_class=<num_classes_in_charades>)
```

**Comment by kalyanvasudev** [comment]
@lyttonhao , could you also please provide some context for the Questions(1-3) raised by @gorjanradevski ?
I think we need documentation on non-kinetics model zoo models. Maybe even have separate model builder functions in model zoo for other datasets?

**Comment by gorjanradevski** [comment]
> @TianhaoFu , this error is correct and expected behaviour for above codesnippet. If you loading a Charades trained model, make sure you pass in additional overrides that are required for that particular model.
> 
> i.e, for Charades, you above snippet should be modified as,
> 
> ```python
> slowfast = _slowfast(pretrained=True, checkpoint_path=checkpoint_path, model_num_class=<num_classes_in_charades>)
> ```

That's strange, since when I pass `model_num_class = 157`, then I get an error:
`
RuntimeError: Error(s) in loading state_dict for Net:
	size mismatch for blocks.6.proj.weight: copying a param with shape torch.Size([400, 2304]) from checkpoint, the shape in current model is torch.Size([157, 2304]).
	size mismatch for blocks.6.proj.bias: copying a param with shape torch.Size([400]) from checkpoint, the shape in current model is torch.Size([157]).
`

The code snippet is:

```python
from pytorchvideo.models.hub.slowfast import _slowfast
import torch

root_url = "https://dl.fbaipublicfiles.com/pytorchvideo/model_zoo"
checkpoint_path = f"{root_url}/charades/SLOWFAST_8x8_R50.pyth"
slowfast = _slowfast(pretrained=True, checkpoint_path=checkpoint_path, model_num_class=157)
```

The dependencies installed are:

```yaml
torch = "^1.9.0"
torchvision = "^0.10.0"
pytorchvideo = "^0.1.1"
```

**Comment by lyttonhao** [comment]
Hi @gorjanradevski, I have tried to load charades checkpoint from my side. I think the current issue is because the old cached kinetics model. So you must have used kinetics model and `torch.hub.load_state_dict_from_url` in `_slowfast` is loading cached Kinetics model instead of downloading the new charades checkpoint as the function seems only check the file name.

So we will find a way to resolve the name conflict in PytorchVideo. For your use case, currently a quick workaround is that you can clear the cache (which usually sits in `~/.cache/torch/hub/checkpoints/`. Or you can manually download the charades checkpoint first and then provide the local path to `_slowfast`.

**Comment by lyttonhao** [comment]
Regarding to the preprocessing of videos, we will add more documents about that. Right now, as we mentioned in the model zoo doc, the pre-trained models are benchmarked in [PySlowFast](https://github.com/facebookresearch/SlowFast/blob/master/projects/pytorchvideo/README.md). For example, for the Slowfast_8x8_r50 model in charades, you can refer to the training details in the [charades dataset](https://github.com/facebookresearch/SlowFast/blob/master/slowfast/datasets/ptv_datasets.py#L311) and [training config](https://github.com/facebookresearch/SlowFast/blob/master/configs/Charades/pytorchvideo/SLOWFAST_8x8_R50.yaml).

**Comment by gorjanradevski** [comment]
Thanks @lyttonhao, I should have seen that one myself. I do not wish to train a model from scratch, but rather just reproduce the inference results. Therefore, it appears that I've everything I need. I'll close the issue now, and in case I need some further pointers I'll just reopen it.
