### ISSUE TITLE
TypeError: 'int' object is not callable

### ISSUE THREAD

**Issue by qianjinhao** [facebookresearch/pytorchvideo#71]
File "train.py", line 349, in __len__
    return self.dataset.num_videos()
TypeError: 'int' object is not callable

**Comment by haooooooqi** [comment]
Hi @qianjinhao,

Thanks for playing with PyTorchVideo! Could you please share me the full stack trace error?

**Comment by kalyanvasudev** [comment]
Closing the issue since it has been resolved in the tagged PR. Please re-open the issue if you have any further questions.
