### ISSUE TITLE
How do i load part of model weight that pulbic in torch.hub to train my video classification model?

### ISSUE THREAD

**Issue by qianjinhao** [facebookresearch/pytorchvideo#75]
I want to train my own video classification model, but I don't know how to load part of the pre-trained model. All I find is create_resnet and creat_slowfast ?

**Comment by kalyanvasudev** [comment]
Hi, could you please elaborate the exact parts of the model you want change? Like head?
Please take a look at this issue on how to change head for pre-trained models- https://github.com/facebookresearch/pytorchvideo/issues/51

Please let me know if this use case doesnt solve your needs.

**Comment by qianjinhao** [comment]
> Hi, could you please elaborate the exact parts of the model you want change? Like head?
> Please take a look at this issue on how to change head for pre-trained models- #51
> 
> Please let me know if this use case doesnt solve your needs.

Thank you for your reply! It helps me a lot. Can you tell me how to use the C2D or I3D model?

**Comment by kalyanvasudev** [comment]
@qianjinhao , you can load pretrained c2d and I3d models using these functions - https://github.com/facebookresearch/pytorchvideo/blob/master/pytorchvideo/models/hub/resnet.py#L93
https://github.com/facebookresearch/pytorchvideo/blob/master/pytorchvideo/models/hub/resnet.py#L126

**Comment by qianjinhao** [comment]
> @qianjinhao , you can load pretrained c2d and I3d models using these functions - https://github.com/facebookresearch/pytorchvideo/blob/master/pytorchvideo/models/hub/resnet.py#L93
> https://github.com/facebookresearch/pytorchvideo/blob/master/pytorchvideo/models/hub/resnet.py#L126

Thanks!

**Comment by kalyanvasudev** [comment]
Please feel free to re-open the issue if you have any further questions.
