### ISSUE TITLE
How to fine tune Slowfast Kinetics model 

### ISSUE THREAD

**Issue by Abiems** [facebookresearch/pytorchvideo#76]
Hi, 

I want to train the slowfast model SLOWFAST_8x8_R50 with my own dataset ( 9 classes of actions) , could you provide Fine/tune code?
thanks alot.

**Comment by kalyanvasudev** [comment]
An example on how to finetune can be found in this PR - https://github.com/facebookresearch/pytorchvideo/pull/41
I will also merge this PR into the mair repo soon.

**Comment by fcakyon** [comment]
@kalyanvasudev is this repo deprecated, why is that PR not merged yet?
