### ISSUE TITLE
ColorJitter is not compatible with ApplyTransformToKey(key="video")

### ISSUE THREAD

**Issue by miraodasilva** [facebookresearch/pytorchvideo#79]
As described in some of your tutorials, I typically use torchvision transformations which I compose and then feed into ApplyTransformToKey. I have tried many, and they all seem to work. 

However, it seems ColorJitter (from torchvision.transforms) is the first that does not work. It confuses the time dimension with the channel dimension in the tensor, and therefore says "TypeError: Input image tensor permitted channel values are [3], but found 30".

I was wondering, is this intended behavior? If so, is there any way I can make ColorJitter work for video with pytorchvideo?

Thanks a lot in advance!

**Comment by kalyanvasudev** [comment]
Hi, One easy fix when you are using `ApplyTransformToKey` and composing transforms is use `torchvision.transforms. Lambda` to permute the video clip tensor before and after the `torchvision.transforms.ColorJitter`.

i.e your code inside ApplyTransformToKey would look something like this,
```
train_transform = Compose(
            [
            ApplyTransformToKey(
              key="video",
              transform=Compose(
                  [
                    UniformTemporalSubsample(8),
                    Lambda(lambda x: x / 255.0),
                    Lambda(lambda x: x.permute((0, 2, 3, 4, 1))), # N C T H W to N T C H W
                    ColorJitter(...)
                    Lambda(lambda x: x.permute((0, 4, 1, 2, 3))), # N T C H W to N C T H W
                    Normalize((0.45, 0.45, 0.45), (0.225, 0.225, 0.225)),
                    RandomShortSideScale(min_size=256, max_size=320),
                    RandomCrop(244),
                    RandomHorizontalFlip(p=0.5),
                  ]
                ),
              ),
            ]
        )
```


I hope this answers your question. Please feel free to re-open the issue if the problem persists.
