### ISSUE TITLE
Kinetics data loader

### ISSUE THREAD

**Issue by danikv** [facebookresearch/pytorchvideo#83]
I tried to use the tutorial provided in the documentation "Training a PyTorchVideo classification model" using the kinetics dataset.
in the official annotation file I noticed there are 2 columns "time_start" and "time_end" which explains when the activity occurs. I didn't see any mention for that in the LabeledVideoDataset class, you just expect the csv to contain "video_path , label".
so my question is , do you assume the videos are already cropped in the right time ? or you don't care about the frame labels and you feed just a random crop of the video and you assume that the activity is contained in that ?
By the way, the official script for downloading the kinetics dataset doesn't work at list for me(I couldn't initialize new conda env with the environment file provided by them, and even after installing by hand the package the script doesn't do anything).

**Comment by duduheihei** [comment]
Have the same question..

**Comment by kalyanvasudev** [comment]
Hi, good questions! 

Yes, we already assume the videos are time cropped accordingly. We have scripts to preprocess and extract clips from videos in the original dataset. For more details on how to do it, please checkout our Kinetics downloading and preprocessing instructions here - https://pytorchvideo.readthedocs.io/en/latest/data_preparation.html#kinetics

**Comment by kalyanvasudev** [comment]
Please re-open the issue if you have more questions or the problem persists. Thanks for trying out PyTorchVideo!
