### ISSUE TITLE
Kinetics' frame dataset

### ISSUE THREAD

**Issue by qianjinhao** [facebookresearch/pytorchvideo#84]
I am using my own data set for training. The previous data is similar to Kinetics' mp4 storage method. Now I want to convert mp4 to video frames, and each folder contains jpg format video frames. How can I modify the code?

**Comment by kalyanvasudev** [comment]
Hi, Our [`LabeledVideoDataset` class](https://github.com/facebookresearch/pytorchvideo/blob/master/pytorchvideo/data/labeled_video_dataset.py) is the core of all of our video dataloaders. It can handle both videos represented as sequence of frames (i.e, .png, .jpg, etc) and encoded video files (i.e, .mp4, .avi, etc)

A good example of a dataloader that uses videos given as frames would be - [AVA dataloader](https://github.com/facebookresearch/pytorchvideo/blob/master/pytorchvideo/data/ava.py#L322) and [Charades dataloader](https://github.com/facebookresearch/pytorchvideo/blob/master/pytorchvideo/data/charades.py#L19).

I hope this gives you an idea on how to create dataloaders for your custom frames dataset using PyTorchVideo components. 

Please feel free to re-open the issue if you have any further questions.
