### ISSUE TITLE
How to use imagenet pretrained resnet weight to initialize model weights?

### ISSUE THREAD

**Issue by qianjinhao** [facebookresearch/pytorchvideo#90]
I want to train a smaller resnet18 network for video classification, and I want to initialize the weights with the resnet18 model of imagenet pretrianed.

**Comment by kalyanvasudev** [comment]
Hi, I'm not sure if I follow you, do mean that you want to intialize video resnet model weights(uses conv3d)  with image resnet model (uses conv2d) weights?

**Comment by qianjinhao** [comment]
> Hi, I'm not sure if I follow you, do mean that you want to intialize video resnet model weights(uses conv3d) with image resnet model (uses conv2d) weights?

yes

**Comment by kalyanvasudev** [comment]
Please take a look at how it is done in SLowFast here - https://github.com/facebookresearch/SlowFast/blob/main/slowfast/utils/checkpoint.py#L142
This feature is not directly related and easily implementable by yourselves. So, closing the issue.
