### ISSUE TITLE
Slack invitation link is expired

### ISSUE THREAD

**Issue by aniketmaurya** [facebookresearch/pytorchvideo#91]
## ❓ Questions on how to use PyTorchVideo
Not able to join slack workspace

NOTE: Please look at the existing list of Issues tagged with the label ['question`](https://github.com/facebookresearch/pytorchvideo/issues?q=label%3Aquestion) or ['how-to`](https://github.com/facebookresearch/pytorchvideo/issues?q=label%3A%22how+to%22). **Only open a new issue if you cannot find an answer there**.

Also note the following:

1. If you encountered any errors or unexpected issues while using PyTorchVideo and need help resolving them,
   please use the "Bugs / Unexpected behaviors" issue template.

2. We do not answer general machine learning / computer vision questions that are not specific to
	 PyTorchVideo, such as how a model works or what algorithm/methods can be
	 used to achieve X.

**Comment by kalyanvasudev** [comment]
Thanks for pointing it out! I will update the link.

**Comment by kalyanvasudev** [comment]
Resolved. Please let me know if you see this issue again. THanks!
