### ISSUE TITLE
RuntimeError: DataLoader worker (pid(s)

### ISSUE THREAD

**Issue by wenjun90** [facebookresearch/pytorchvideo#94]
Hello @kalyanvasudev ,

Thank you for your great job. I have a question for you, please?

I have set the configuration like that:
dm = make_video_datamodule(batch_size=8, num_workers=8)
def make_slowr50_finetuner(num_labels, freeze_backbone=True):
    '''Init Pretrained Model, freeze its backbone, and replace its classification head'''
    model = torch.hub.load("facebookresearch/pytorchvideo", "slow_r50", pretrained=True)
    model.blocks[:-1].requires_grad_(not freeze_backbone)
    model.blocks[-1] = create_res_basic_head(in_features=2048, out_features=num_labels)
    return model
model = make_slowr50_finetuner(dm.num_labels)
classifier = Classifier(model, lr=2e-4)
trainer = pl.Trainer(gpus=1, precision=16, max_epochs=5, callbacks=[checkpoint_callback])
trainer.fit(classifier, dm)

But after several epochs (about 5 epochs), there is always error like that:

_File "/home/miniconda3/lib/python3.9/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 3155823) is killed by signal: Killed. 

  File "/home/miniconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1003, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 3155823) exited unexpectedly_

How to we can fix this error?

When I set worker = 0, there is no problem but time of training is so long.

Thank you very much?

**Comment by kalyanvasudev** [comment]
Hi @wenjun90 , it could be also your systems memory constraints not being able to accommodate multiple workers.

To pin point the problem, and weed-out that shared memory is not the problem, could you try with with a smaller batch size and set worker >0 but a small number ?

**Comment by kalyanvasudev** [comment]
Closing the issue due to inactivity. Please refer to our later PyTorchLightning VIdeo trainer for more details on how to train video models using Lightning  - https://github.com/facebookresearch/pytorchvideo/pull/158
