### ISSUE TITLE
AttributeError: module 'pytorchvideo' has no attribute 'transforms'

### ISSUE THREAD

**Issue by GalSang17** [facebookresearch/pytorchvideo#97]
## ❓ Questions on how to use PyTorchVideo

NOTE: Please look at the existing list of Issues tagged with the label ['question`](https://github.com/facebookresearch/pytorchvideo/issues?q=label%3Aquestion) or ['how-to`](https://github.com/facebookresearch/pytorchvideo/issues?q=label%3A%22how+to%22). **Only open a new issue if you cannot find an answer there**.

Also note the following:

1. If you encountered any errors or unexpected issues while using PyTorchVideo and need help resolving them,
   please use the "Bugs / Unexpected behaviors" issue template.

2. We do not answer general machine learning / computer vision questions that are not specific to
	 PyTorchVideo, such as how a model works or what algorithm/methods can be
	 used to achieve X.
![image](https://user-images.githubusercontent.com/49866330/128281417-84e0f963-6838-4c57-974b-3518ddb57072.png)

**Comment by kalyanvasudev** [comment]
@GalSang17 , I'm unable to reporduce this error and all the tests seem to be passing. What was your exact setup? How did you install PyTorchVideo?

**Comment by kalyanvasudev** [comment]
Closing the issue due to inactivity.

**Comment by shalini-maiti** [comment]
Hi, I have the same issue but I have installed pytorchvideo with python=3.10.6. Is it not compatible?
