### ISSUE TITLE
AVA dataset possible bug

### ISSUE THREAD

**Issue by anisaha1** [facebookresearch/pytorchvideo#99]
Hi @kalyanvasudev,

I believe 
```python
if (
      frame_sec > AvaLabeledVideoFramePaths.AVA_VALID_FRAMES[1]
      or frame_sec < AvaLabeledVideoFramePaths.AVA_VALID_FRAMES[0]
  ):
      continue
```

should change to 
```python
if (
      frame_sec > AvaLabeledVideoFramePaths.AVA_VALID_FRAMES[-1]
      or frame_sec < AvaLabeledVideoFramePaths.AVA_VALID_FRAMES[0]
  ):
      continue
```

[here](https://github.com/facebookresearch/pytorchvideo/blob/a0230a615a59e2ebe68b63ab22c1e2e940f6b320/pytorchvideo/data/ava.py#L171).

Could you please verify?

Another possible way to write it would be like [this](https://github.com/facebookresearch/SlowFast/blob/master/slowfast/datasets/ava_helper.py#L145).

**Comment by kalyanvasudev** [comment]
Yes, the suggested fix is correct. Thanks!

**Comment by kalyanvasudev** [comment]
resolved.
